[package]
name = "glang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["cargo"] }
console = "0.15.8"
thiserror = "1.0.57"

[dev-dependencies]
assert_matches = "1.5.0"
rstest = "0.18.2"


[profile.release]
opt-level = 3
lto = true
